### ISSUE TITLE
Whisper on AndroidGPU

### ISSUE THREAD

**Issue by sandorkonya** [MarcoCiaramella/AndroidGPU#1]
@MarcoCiaramella hi there,
nice work on utilizing the GPU on Android!

Do you see any possibility to integrate your efforts with another project? 
It would be really cool to see Whisper working on Android with Vulkan support instead of CPU only!

A roadmap had been posted recently [here](https://github.com/ggerganov/llama.cpp/discussions/1729) where they are seeking some help with Vulkan:

> For example, it would be interesting if we can add a WebGPU or Vulkan backends in a similar way as we did with metal . I'm completely unfamiliar with the details of these frameworks, but I'm hoping that people might be interested in giving it a try

thanks for viewing!

**Comment by MarcoCiaramella** [comment]
@sandorkonya hello, thanks for your interest! I will check the roadmp asap and write you back here.

**Comment by MarcoCiaramella** [comment]
@sandorkonya reading the roadmap I see that there is only a Metal implementaion that runs the llma over a GPU. So you need a Vulkan implementaion before and then you can try to use the same compute shader with this module AndroidGPU or use the code of this module as starting point for the Android version. I'm not able to do this stuff starting from Metal, sorry.

**Comment by sandorkonya** [comment]
> @sandorkonya reading the roadmap I see that there is only a Metal implementaion that runs the llma over a GPU. So you need a Vulkan implementaion before and then you can try to use the same compute shader with this module AndroidGPU or use the code of this module as starting point for the Android version. I'm not able to do this stuff starting from Metal, sorry.

Hey, thank you for looking at it!
I'll keep my eyes open for the Vulkan implementation, and might get back to you with questions!
Take care!
regards
